### ISSUE TITLE
AttributeError: 'module' object has no attribute 'config'

### ISSUE THREAD

**Issue by shermansiu** [SublimeLinter/SublimeLinter-pydocstyle#20]
SublimeLinter-pydocstyle keeps throwing the following error when linting.

```python
Traceback (most recent call last):
  File "/Users/ss985/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ss985/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/python_linter.py", line 285, in run
    errors = self.check(code, os.path.basename(self.filename or '<unsaved>'))
  File "linter in /Users/ss985/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-pydocstyle.sublime-package", line 73, in check
AttributeError: 'module' object has no attribute 'config'
```

Miscellaneous debugging information
---
The `sys.executable` is `python3`.
```bash
$ whoami
$ which pydocstyle
/usr/local/bin/pydocstyle
$ pydocstyle --version
2.1.1
```
And if I try to access `pydocstyle.config` through the Python terminal, it works.
```python
Python 3.6.4 (default, Jan  6 2018, 11:51:15)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydocstyle
>>> pydocstyle.config
<module 'pydocstyle.config' from '/usr/local/lib/python3.6/site-packages/pydocstyle/config.py'>
```

I have configured SublimeLinter to use Python 3 in my SublimeLinter.sublime-settings
```json
"@python": 3
```

**Comment by kaste** [comment]
Hi! Ist this a regression from our last update or are you a new user and it never worked?

**Comment by shermansiu** [comment]
It has worked in the past.

I disabled the "Python Flake8 Lint" package and it is now working as it used to.

Thanks anyway!
