### ISSUE TITLE
Does not work at all with Sublime 3.1.1

### ISSUE THREAD

**Issue by MartinThoma** [SublimeLinter/SublimeLinter-pydocstyle#25]
I can't see anything happening. There also is no configuration for it - so I guess something is broken with pydocstyle.

```
reloading plugin SublimeLinter-contrib-mypy.linter
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/home/math/.config/sublime-text-3/Installed Packages/SublimeLinter-contrib-mypy.sublime-package/linter.py", line 21, in <module>
ImportError: No module named 'SublimeLinter'
reloading plugin SublimeLinter-contrib-protoc-gen-lint.linter
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/home/math/.config/sublime-text-3/Installed Packages/SublimeLinter-contrib-protoc-gen-lint.sublime-package/linter.py", line 12, in <module>
ImportError: No module named 'SublimeLinter'
reloading plugin SublimeLinter-pydocstyle.linter
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/home/math/.config/sublime-text-3/Installed Packages/SublimeLinter-pydocstyle.sublime-package/linter.py", line 1, in <module>
ImportError: No module named 'SublimeLinter'
```

**Comment by kaste** [comment]
Please make sure to install SublimeLinter first
